/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolicitudMaterialesBodega;

import BD.SolicitudesBodegaClass;
import Class.ClassTrabajos;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class CalculoIndicador extends javax.swing.JInternalFrame {

    /**
     * Creates new form CalculoIndicador
     */
    public CalculoIndicador() {
        initComponents();
        //trab.setDefaultRenderer (Object.class, new FormatoTabla());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        INICIO = new com.toedter.calendar.JDateChooser();
        FIN = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        trab = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("CALCULO INDICADOR DE BODEGA");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ComponenteImagenes/Search.png"))); // NOI18N
        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        trab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(trab);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("DEL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("AL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FIN, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1336, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INICIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(FIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
          
        if (INICIO.getDate() != null && FIN.getDate() != null) {

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yy");
            Date fec1 = INICIO.getDate();
            Date fec2 = FIN.getDate();
            String fe1 = formato.format(fec1);
            String fe2 = formato.format(fec2);
            try {
                Date f1 = formato.parse(fe1);
                Date f2 = formato.parse(fe2);

                if (f1.before(f2)) {
                  
                ListarTrabajosIndicador();
                

                } else {
                    JOptionPane.showMessageDialog(null, "LA PRIMERA FECHA NO PUEDE SER MAYOR A LA SEGUNDA FECHA");
                }

            } catch (ParseException ex) {
                Logger.getLogger(CalculoIndicador.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE LAS FECHAS...");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

  private void ListarTrabajosIndicador(){
      
        Date date = INICIO.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
        String fecha = sdf.format(date);
        
        Date date2 = FIN.getDate();
        SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yy");
        String fecha1 = sd.format(date2);
      
      
        ArrayList<ClassTrabajos> result = SolicitudesBodegaClass.ListarHistorialCalculoIndicador(fecha,fecha1);
        RecargarTabla1(result);  
    }
     private void RecargarTabla1(ArrayList<ClassTrabajos> list) {
         
              Object[][] datos = new Object[list.size()][11];
              int i = 0;
              for(ClassTrabajos t : list)
              {
                  datos[i][0] = t.getId();
                  datos[i][1] = t.getNOLOTE();
                  datos[i][2] = t.getPN();
                  datos[i][3] = t.getJob();
                  datos[i][4] = t.getCliente();
                  datos[i][5] = t.getEstandar();
                  datos[i][6] = t.getRevision();
                  datos[i][7] = t.getQTYPORLOTE();
                  datos[i][8] = t.getFecha();
                  datos[i][9] = t.getFecha2();
                  datos[i][10] = t.getDiasPro();
                  i++;
              }    
             trab.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                " ","NO. LOTE","P/N","JOB","CLIENTE","ESTANDAR","REVISION","CANTIDAD","FECHA SOLICITUD","FECHA ENTREGA","DIAS"

             })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = trab.getColumn(" ");
             columna1.setPreferredWidth(-10);
             TableColumn columna2 = trab.getColumn("NO. LOTE");
             columna2.setPreferredWidth(50);
             TableColumn columna3 = trab.getColumn("P/N");
             columna3.setPreferredWidth(50);
             TableColumn columna4 = trab.getColumn("JOB");
             columna4.setPreferredWidth(50);
             TableColumn columna5 = trab.getColumn("CLIENTE");
             columna5.setPreferredWidth(50);
             TableColumn columna6 = trab.getColumn("ESTANDAR");
             columna6.setPreferredWidth(60);
             TableColumn columna7 = trab.getColumn("REVISION");
             columna7.setPreferredWidth(50);
             TableColumn columna8 = trab.getColumn("CANTIDAD");
             columna8.setPreferredWidth(50);
             
}       
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FIN;
    private com.toedter.calendar.JDateChooser INICIO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable trab;
    // End of variables declaration//GEN-END:variables
}
