/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Envios;

import ClassEnvios.BDEnvios;
import ClassEnvios.ClassEnv;
import java.util.ArrayList;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class ListadoEnvios extends javax.swing.JInternalFrame {
      int NO;
    /**
     * Creates new form ListadoEnvios
     */
    public ListadoEnvios() {
        initComponents();
        ListarEnvios();
        CONTROL.setDefaultRenderer (Object.class, new FormatoTablaEnvios());
    }
    
 //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////   
    private void ListarEnvios() {
        ArrayList<ClassEnv> result = BDEnvios.ListarEnvios();
        recargarTable(result);
    }
    
    public void recargarTable(ArrayList<ClassEnv> list) {
        Object[][] datos = new Object[list.size()][2];
        int i = 0;
        for (ClassEnv m : list)
        {
            datos[i][0] = m.getNo_envio();
            datos[i][1] = m.getFecha();
            i++;
        }
        ENVIOS.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    "No.","FECHA"
                }) {
                     @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        TableColumn columna1 = ENVIOS.getColumn("No.");
             columna1.setPreferredWidth(0);
             TableColumn columna2 = ENVIOS.getColumn("FECHA");
             columna2.setPreferredWidth(85);
    }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

private void ListarTrabajosdeEnvio(){
        ArrayList<ClassEnv> result = BDEnvios.ListadoParaelEnvio(NO);
        TablaEnvi(result);  
    }
     private void TablaEnvi(ArrayList<ClassEnv> list) {
         
              Object[][] datos = new Object[list.size()][11];
              int i = 0;
              for(ClassEnv t : list)
              {
                  datos[i][0] = t.getJob();
                  datos[i][1] = t.getPN();
                  datos[i][2] = t.getLoteS();
                  datos[i][3] = t.getProcesosActual();
                  datos[i][4] = t.getCantidad();
                  datos[i][5] = t.getFecha();
                  datos[i][6] = t.getDatecode();
                  datos[i][7] = t.getSN();
                  datos[i][8] = t.getSN1();
                  datos[i][9] = t.getFechadata();
                  datos[i][10] = t.getFechadata();
                  i++;
              }    
             CONTROL.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                "JOB","P/N","LOTE","PROCESO ACTUAL","QTY","FECHA","DATE CODE","S/N","","FECHA PARA DATA"
             })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             
             TableColumn columna1 = CONTROL.getColumn("JOB");
             columna1.setPreferredWidth(0);
             TableColumn columna2 = CONTROL.getColumn("P/N");
             columna2.setPreferredWidth(0);
             TableColumn columna3 = CONTROL.getColumn("LOTE");
             columna3.setPreferredWidth(0);
             TableColumn columna4 = CONTROL.getColumn("PROCESO ACTUAL");
             columna4.setPreferredWidth(200);
             TableColumn columna6 = CONTROL.getColumn("QTY");
             columna6.setPreferredWidth(0);
             TableColumn columna7 = CONTROL.getColumn("FECHA");
             columna7.setPreferredWidth(100);
             TableColumn columna8 = CONTROL.getColumn("DATE CODE");
             columna8.setPreferredWidth(0);
             TableColumn columna9 = CONTROL.getColumn("S/N");
             columna9.setPreferredWidth(0);
             TableColumn columna10 = CONTROL.getColumn("");
             columna10.setPreferredWidth(0);
             TableColumn columna11 = CONTROL.getColumn("FECHA PARA DATA");
             columna11.setPreferredWidth(300);
             
}        
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CONTROL = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        ENVIOS = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("CONTROL DE ORDENES PARA LOS ENVIOS");

        CONTROL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CONTROL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JOB", "P/N", "LOTE", "PROCESO ACTUAL", "QTY", "FECHA", "DATE CODE", "S/N", "", "FECHA PARA DATA"
            }
        ));
        CONTROL.setRowHeight(25);
        jScrollPane1.setViewportView(CONTROL);

        ENVIOS.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ENVIOS.setForeground(new java.awt.Color(255, 51, 0));
        ENVIOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA DE ENVIO"
            }
        ));
        ENVIOS.setIntercellSpacing(new java.awt.Dimension(15, 1));
        ENVIOS.setRowHeight(25);
        ENVIOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENVIOSMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ENVIOS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ENVIOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENVIOSMouseClicked
         NO = (int) ENVIOS.getModel().getValueAt(ENVIOS.getSelectedRow(), 0);
        ListarTrabajosdeEnvio();
    }//GEN-LAST:event_ENVIOSMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CONTROL;
    private javax.swing.JTable ENVIOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
