/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolicitudesMateriales;

import BD.BD;
import BD.InsertarProductosTaller;
import BD.ProductosTaller;
import Formularios.Inicio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class ConsultadePedidos extends javax.swing.JInternalFrame {
     int idlote;
     int idpedido;
     int idpedido1;
     int depto;
     int idloteejemplo;
    /**
     * Creates new form STATUS
     */
    public ConsultadePedidos() {
        initComponents();
        Trabajos.setDefaultRenderer (Object.class, new FormatoTabla());
        TrabajosEjemplos.setDefaultRenderer (Object.class, new FormatoTabla());
        selectusuario();
        ListarTrabajos();
        ListarTrabajosEjemplos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void selectusuario() {
        String a = System.getProperty("user.name");//usar usuario de windows
        if (a.equals("jluis")) {
            depto = 1;
        } //INFORMATICA
        else if (a.equals("ehernandez")) {
            depto = 1;
        } //TRANSFORMADORES
        else if (a.equals("ingenieria2")) {
            depto = 2;
        } //INGENIERIA
        else if (a.equals("potting")) {
            depto = 3;
        } //STRIP & POTTING
        else if (a.equals("Inspeccion")) {
            depto = 4;
        }// INSPECCION
        else if (a.equals("testing")) {
            depto = 5;
        } // TESTING
        else if (a.equals("calidad")) {
            depto = 6;
        } // CALIDAD 
        else if (a.equals("oecheverria")) {
            depto = 7;
        }//GERENTE OPERACIONES
        else if (a.equals("bodega")) {
            depto = 8;
        }//BODEGA 
        else if (a.equals("ingenieria")) {
            depto = 9;
        }//RELACION CON EL CLIENTE 
        else if(a.equals("taller")){
            depto = 10;
        }//TALLER
        else if(a.equals("Sotano")){
            depto = 10;
        }//TALLER
        else if(a.equals("apacheco")){
            depto = 11;
        }
        else if(a.equals("deptochips")){
            depto = 12;
            
        }
    }    
    
    
    
    private void ListarTrabajos(){
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosPendientesConsultaMaster(PN.getText());
        RecargarTabla(result);  
    }
     private void RecargarTabla(ArrayList<ProductosTaller> list) {
         
              Object[][] datos = new Object[list.size()][6];
              int i = 0;
              for(ProductosTaller t : list)
              {
                  datos[i][0] = t.getIdlote();
                  datos[i][1] = t.getPN();
                  datos[i][2] = t.getJOB();
                  datos[i][3] = t.getNolote();
                  datos[i][4] = t.getCantidad();
                  datos[i][5] = t.getPrioridad();
                  i++;
              }    
             Trabajos.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                " ","P/N","JOB","NO. LOTE","CANTIDAD","PRIORIDAD"           })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = Trabajos.getColumn(" ");
             columna1.setPreferredWidth(-20);
             TableColumn columna2 = Trabajos.getColumn("P/N");
             columna2.setPreferredWidth(75);
             TableColumn columna3 = Trabajos.getColumn("JOB");
             columna3.setPreferredWidth(75);
             TableColumn columna4 = Trabajos.getColumn("NO. LOTE");
             columna4.setPreferredWidth(75);
             TableColumn columna5 = Trabajos.getColumn("CANTIDAD");
             columna5.setPreferredWidth(75);   
             }    
     
     
     private void ListarTrabajosEjemplos(){
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarTrabajosEjemploMaster(PN1.getText());
        RecargarTablaE(result);  
    }
     private void RecargarTablaE(ArrayList<ProductosTaller> list) {
         
              Object[][] datos = new Object[list.size()][6];
              int i = 0;
              for(ProductosTaller t : list)
              {
                  datos[i][0] = t.getIdlote();
                  datos[i][1] = t.getPN();
                  datos[i][2] = t.getJOB();
                  datos[i][3] = t.getEstatus();
                  datos[i][4] = t.getCantidad();
                  datos[i][5] = t.getPrioridad();
                  i++;
              }    
             TrabajosEjemplos.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                " ","P/N","JOB","NO. LOTE","CANTIDAD","PRIORIDAD"           })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = TrabajosEjemplos.getColumn(" ");
             columna1.setPreferredWidth(-20);
             TableColumn columna2 = TrabajosEjemplos.getColumn("P/N");
             columna2.setPreferredWidth(75);
             TableColumn columna3 = TrabajosEjemplos.getColumn("JOB");
             columna3.setPreferredWidth(75);
             TableColumn columna4 = TrabajosEjemplos.getColumn("NO. LOTE");
             columna4.setPreferredWidth(75);
             TableColumn columna5 = TrabajosEjemplos.getColumn("CANTIDAD");
             columna5.setPreferredWidth(75);   
             }    
    
     private void ListarProductosTrabajos(){
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosTrabajoMaster(idlote);
        RecargarTablaProductos(result);  
    }
     private void RecargarTablaProductos(ArrayList<ProductosTaller> list){
         
              Object[][] datos = new Object[list.size()][7];
              int i = 0;
              for(ProductosTaller t : list)
              {
                  datos[i][0] = t.getIdpedido();
                  datos[i][1] = t.getDescripcion();
                  datos[i][2] = t.getCantidad();
                  datos[i][3] = t.getEstatus();
                  datos[i][4] = t.getDepartamento();
                  datos[i][5] = t.getFechaStrin();
                  datos[i][6] = t.getNota();
                  i++;
              }    
             PENDIENTES.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                " ","DESCRIPCION","CANTIDAD","ESTATUS","DEPARTAMENTO","FECHA SOLICITADO","NOTA"      })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = PENDIENTES.getColumn(" ");
             columna1.setPreferredWidth(0);
             TableColumn columna2 = PENDIENTES.getColumn("DESCRIPCION");
             columna2.setPreferredWidth(100);
             TableColumn columna3 = PENDIENTES.getColumn("CANTIDAD");
             columna3.setPreferredWidth(50);
             TableColumn columna4 = PENDIENTES.getColumn("ESTATUS");
             columna4.setPreferredWidth(120);
             TableColumn columna5 = PENDIENTES.getColumn("FECHA SOLICITADO");
             columna5.setPreferredWidth(100);
             TableColumn columna6 = PENDIENTES.getColumn("NOTA");
             columna6.setPreferredWidth(150);
             }
     
     
     
     private void ListarProductosTrabajosEjemplos(){
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosTrabajoEjemploMaster(idloteejemplo);
        RecargarTablaProductoseje(result);  
    }
     private void RecargarTablaProductoseje(ArrayList<ProductosTaller> list){
         
              Object[][] datos = new Object[list.size()][7];
              int i = 0;
              for(ProductosTaller t : list)
              {
                  datos[i][0] = t.getIdpedido();
                  datos[i][1] = t.getDescripcion();
                  datos[i][2] = t.getCantidad();
                  datos[i][3] = t.getEstatus();
                  datos[i][4] = t.getDepartamento();
                  datos[i][5] = t.getFechaStrin();
                  datos[i][6] = t.getNota();
                  i++;
              }    
             PENDIENTESEjemplo.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                " ","DESCRIPCION","CANTIDAD","ESTATUS","DEPARTAMENTO","FECHA SOLICITUD","NOTA"       })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = PENDIENTESEjemplo.getColumn(" ");
             columna1.setPreferredWidth(0);
             TableColumn columna2 = PENDIENTESEjemplo.getColumn("DESCRIPCION");
             columna2.setPreferredWidth(100);
             TableColumn columna3 = PENDIENTESEjemplo.getColumn("CANTIDAD");
             columna3.setPreferredWidth(50);
             TableColumn columna4 = PENDIENTESEjemplo.getColumn("ESTATUS");
             columna4.setPreferredWidth(120);
             TableColumn columna5 = PENDIENTES.getColumn("FECHA SOLICITADO");
             columna5.setPreferredWidth(100);
             TableColumn columna6 = PENDIENTES.getColumn("NOTA");
             columna6.setPreferredWidth(150);
             }
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Trabajos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        PENDIENTES = new javax.swing.JTable();
        PN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TrabajosEjemplos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        PENDIENTESEjemplo = new javax.swing.JTable();
        PN1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        aceptar1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("LISTADO DE PEDIDOS A TALLER");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        Trabajos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "P/N", "JOB", "LOTE", "CANTIDAD"
            }
        ));
        Trabajos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrabajosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Trabajos);

        PENDIENTES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PENDIENTES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PENDIENTESMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PENDIENTES);

        PN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PNKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("P/N");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("TRABAJOS", jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        TrabajosEjemplos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "P/N", "JOB", "LOTE", "CANTIDAD"
            }
        ));
        TrabajosEjemplos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrabajosEjemplosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TrabajosEjemplos);

        PENDIENTESEjemplo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PENDIENTESEjemplo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PENDIENTESEjemploMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(PENDIENTESEjemplo);

        PN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PN1ActionPerformed(evt);
            }
        });
        PN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PN1KeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("P/N");

        aceptar1.setText("ACEPTAR");
        aceptar1.setEnabled(false);
        aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PN1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(aceptar1)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aceptar1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("EJEMPLOS", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PNKeyReleased
       ListarTrabajos();
    }//GEN-LAST:event_PNKeyReleased

    private void TrabajosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrabajosMouseClicked
      idlote = (Integer.parseInt(String.valueOf(Trabajos.getModel().getValueAt(Trabajos.getSelectedRow(), 0))));
      ListarProductosTrabajos();
    }//GEN-LAST:event_TrabajosMouseClicked

    private void PENDIENTESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PENDIENTESMouseClicked
       
      
       
    }//GEN-LAST:event_PENDIENTESMouseClicked

    private void TrabajosEjemplosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrabajosEjemplosMouseClicked
        idloteejemplo = (Integer.parseInt(String.valueOf(TrabajosEjemplos.getModel().getValueAt(TrabajosEjemplos.getSelectedRow(), 0))));
      ListarProductosTrabajosEjemplos();
    }//GEN-LAST:event_TrabajosEjemplosMouseClicked

    private void PENDIENTESEjemploMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PENDIENTESEjemploMouseClicked
      
        String estado1 = (String.valueOf(PENDIENTESEjemplo.getModel().getValueAt(PENDIENTESEjemplo.getSelectedRow(), 3)));
        if(estado1.equals("ENTREGADO")){aceptar1.setEnabled(true);}else{aceptar1.setEnabled(false);}
        
        
    }//GEN-LAST:event_PENDIENTESEjemploMouseClicked

    private void PN1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PN1KeyReleased
       ListarTrabajosEjemplos();
    }//GEN-LAST:event_PN1KeyReleased

    private void aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar1ActionPerformed
      
        idpedido1 = (Integer.parseInt(String.valueOf(PENDIENTESEjemplo.getModel().getValueAt(PENDIENTESEjemplo.getSelectedRow(), 0))));
       try {
    Connection cnn = BD.getConnection();
    PreparedStatement ps = null;
    ps= cnn.prepareStatement("update pedidos_trabajos set status = 4, estado = 2 where id_pedido ="+idpedido1);
    ps.executeUpdate();
    cnn.close();
    ps.close();
      } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }   
       ListarProductosTrabajosEjemplos();
       ListarTrabajosEjemplos();
         
    }//GEN-LAST:event_aceptar1ActionPerformed

    private void PN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PN1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PN1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PENDIENTES;
    private javax.swing.JTable PENDIENTESEjemplo;
    private javax.swing.JTextField PN;
    private javax.swing.JTextField PN1;
    private javax.swing.JTable Trabajos;
    private javax.swing.JTable TrabajosEjemplos;
    private javax.swing.JButton aceptar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
