/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolicitudesMateriales;

import BD.BD;
import BD.InsertarProductosTaller;
import BD.ProductosTaller;
import Formularios.Inicio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class EntregaSolicitud extends javax.swing.JInternalFrame {

    int idlote;
    int idpedido;
    int depto;
    int status;
    int idloteejemplo;
    int id;
    String JobHistorial;
    String pnHistorial;
    int compoHistorial;
    int idpedidoHistorial;
    int cantidadhistorial;
    int realizadohistoria;        
    /**
     * Creates new form STATUS
     */
    public EntregaSolicitud() {
        initComponents();
        Trabajos.setDefaultRenderer (Object.class, new FormatoTabla());
        TrabajosEjemplo.setDefaultRenderer (Object.class, new FormatoTabla());
        ListarTrabajos();
        ListarTrabajosEjemplos();
        selectusuario();
        po.setEnabled(false);
        cantidad.setEnabled(false);
        by.setEnabled(false);
        aceptar.setEnabled(false);
        poInset.setEnabled(false);
        poPot.setEnabled(false);
        
        po2.setEnabled(false);
        cantidad2.setEnabled(false);
        by2.setEnabled(false);
        aceptar3.setEnabled(false);
        poInset1.setEnabled(false);
        poPot1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void selectusuario() {
        String a = System.getProperty("user.name");//usar usuario de windows
        if (a.equals("jluis")) {
            depto = 0;
        } //INFORMATICA
        else if (a.equals("ehernandez")) {
            depto = 1;
        } //TRANSFORMADORES
        else if (a.equals("ingenieria2")) {
            depto = 2;
        } //INGENIERIA
        else if (a.equals("potting")) {
            depto = 3;
        } //STRIP & POTTING
        else if (a.equals("Inspeccion")) {
            depto = 4;
        }// INSPECCION
        else if (a.equals("testing")) {
            depto = 5;
        } // TESTING
        else if (a.equals("calidad")) {
            depto = 6;
        } // CALIDAD 
        else if (a.equals("oecheverria")) {
            depto = 7;
        }//GERENTE OPERACIONES
        else if (a.equals("bodega")) {
            depto = 8;
        }//BODEGA 
        else if (a.equals("ingenieria")) {
            depto = 9;
        }//RELACION CON EL CLIENTE 
        else if (a.equals("taller")) {
            depto = 10;
        }//TALLER
        else if (a.equals("Sotano")) {
            depto = 10;
        }//TALLER
        else if (a.equals("apacheco")) {
            depto = 11;
        } else if (a.equals("deptochips")) {
            depto = 12;

        }
    }

    private void limpiar() {
        po.setText("");
        cantidad.setText("");
        by.setText("");
        nota.setText("");
        descripcion.setText("");
        fechapedi.setText("");
        poInset.setText("");
        poPot.setText("");

    }
    private void limpiarEje() {
        po2.setText("");
        cantidad2.setText("");
        by2.setText("");
        nota2.setText("");
        descripcion2.setText("");
        fechapedi2.setText("");
        poInset1.setText("");
        poPot1.setText("");
    }

    private void llenacuainformacion() {
        try {

            ProductosTaller c = InsertarProductosTaller.buscarTrabajo(Integer.parseInt(String.valueOf(PENDIENTES.getModel().getValueAt(PENDIENTES.getSelectedRow(), 0))));
            id = c.getIdpedido();
            descripcion.setText(c.getDescripcion());
            fechapedi.setText(c.getFechaStrin());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" + e);
        }
    }

    private void llenacuainformacionEjemplo() {
        try {

            ProductosTaller c = InsertarProductosTaller.buscarTrabajo(Integer.parseInt(String.valueOf(PENDIENTESEjemplo.getModel().getValueAt(PENDIENTESEjemplo.getSelectedRow(), 0))));
            id = c.getIdpedido();
            descripcion2.setText(c.getDescripcion());
            fechapedi2.setText(c.getFechaStrin());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" + e);
        }
    }

    private void insertarEntrega() {
        try {
            ProductosTaller t = new ProductosTaller();
            t.setIdpedido(id);
            t.setPO(po.getText());
            t.setCantidad(Integer.parseInt(cantidad.getText()));
            t.setNota(nota.getText());
            t.setBy(Integer.parseInt(by.getText()));
            t.setPOInsert(poInset.getText());
            t.setPOPotRod(poPot.getText());
            InsertarProductosTaller.InsertarEntrega(t);
            JOptionPane.showMessageDialog(null, "Entrega agregada");
            limpiar();
            actualizarTerminado();
            ListarProductosTrabajos();
            ListarTrabajos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" + e);
        }
    }

    private void insertarEntregaEjemplo() {
        try {
            ProductosTaller t = new ProductosTaller();
            t.setIdpedido(id);
            t.setPO(po2.getText());
            t.setCantidad(Integer.parseInt(cantidad2.getText()));
            t.setNota(nota2.getText());
            t.setBy(Integer.parseInt(by2.getText()));
            t.setPOInsert(poInset1.getText());
            t.setPOPotRod(poPot1.getText());
            InsertarProductosTaller.InsertarEntrega(t);
            JOptionPane.showMessageDialog(null, "Entrega agregada");
            limpiarEje();
            actualizarTerminado();
            ListarProductosTrabajosEjemplos();
            ListarTrabajosEjemplos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" + e);
        }
    }

    private void actualizarTerminado() {
        try {
            Connection cnn = BD.getConnection();
            PreparedStatement ps = null;
            ps = cnn.prepareStatement("update pedidos_trabajos set status = 3 where id_pedido =" + id);
            ps.executeUpdate();
            cnn.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void buscarProducto() {
        try {
            Connection con = BD.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select id_producto from pedidos_trabajos where id_pedido=" +idpedidoHistorial);
            while (rs.next()) {
                int lastID = rs.getInt(1);
                compoHistorial = lastID;
            }
            rs.close();
            stmt.close();
            con.close();
        } catch (SQLException error) {
            System.out.print(error + "ERROR PRODUCTO");
        }
    }
    
     private void buscarpo() {
         //System.out.println("JOB = "+JobHistorial);
         //System.out.println("PRODUCTO ="+compoHistorial);
        try {
            Connection con = BD.getConnection();
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select po,poinsert,popotrod,cantidad,realizado from entregas_productos where id_pedido =(select max(p.id_pedido)id from trabajo t inner JOIN lotes l on t.id = l.id \n" +
            "join pedidos_trabajos p on l.id_lote = p.id_lote JOIN entregas_productos e on p.id_pedido = e.id_pedido where t.pn = '"+pnHistorial+"' and t.job = '"+JobHistorial+"' and p.id_producto in ("+compoHistorial+"))");
            while (rs.next()) {
                String PO = rs.getString(1);
                String POInsert = rs.getString(2);
                String POpotrod = rs.getString(3);
                int cantidad = rs.getInt(4);
                int realizado = rs.getInt(5);
                if(PO == null){po.setText("");}else{po.setText(String.valueOf(PO));}
                if( POInsert == null){poInset.setText("");}else{poInset.setText(String.valueOf(POInsert));}
                if( POpotrod == null){poPot.setText("");}else{poPot.setText(String.valueOf(POpotrod));}
                if(cantidad == 0){this.cantidad.setText("");}else{this.cantidad.setText(String.valueOf(cantidad));}
                if(realizado == 0){by.setText("");}else{by.setText(String.valueOf(realizado));}
            }
            rs.close();
            stmt.close();
            con.close();
        } catch (SQLException error) {
            System.out.print(error + "ERROR PO");
        }
    }

    /* private void actualizarEjemplo(){
     idpedido = (Integer.parseInt(String.valueOf(PENDIENTESEjemplo.getModel().getValueAt(PENDIENTESEjemplo.getSelectedRow(), 0))));
       try {
    Connection cnn = BD.getConnection();
    PreparedStatement ps = null;
    ps= cnn.prepareStatement("update pedidos_trabajos set status = "+status+", nota = '"+nota.getText()+"' where id_pedido ="+idpedido);
    ps.executeUpdate();
    cnn.close();
    ps.close();
      } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }   
       ListarProductosTrabajosEjemplos();
       estado1.setEnabled(false);
       nota1.setEnabled(false);
       aceptar1.setEnabled(false);
       estado1.setSelectedItem("");
          
    }*/
    private void ListarTrabajos() {
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosPendientesMaster(PN.getText());
        RecargarTabla(result);
    }

    private void RecargarTabla(ArrayList<ProductosTaller> list) {

        Object[][] datos = new Object[list.size()][5];
        int i = 0;
        for (ProductosTaller t : list) {
            datos[i][0] = t.getIdlote();
            datos[i][1] = t.getPN();
            datos[i][2] = t.getJOB();
            datos[i][3] = t.getEstatus();
            datos[i][4] = t.getCantidad();
            i++;
        }
        Trabajos.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    " ", "P/N", "JOB", "NO. LOTE", "CANTIDAD"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        TableColumn columna1 = Trabajos.getColumn(" ");
        columna1.setPreferredWidth(-20);
        TableColumn columna2 = Trabajos.getColumn("P/N");
        columna2.setPreferredWidth(75);
        TableColumn columna3 = Trabajos.getColumn("JOB");
        columna3.setPreferredWidth(75);
        TableColumn columna4 = Trabajos.getColumn("NO. LOTE");
        columna4.setPreferredWidth(75);
        TableColumn columna5 = Trabajos.getColumn("CANTIDAD");
        columna5.setPreferredWidth(75);
    }

    private void ListarProductosTrabajos(){
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosTrabajoMaster(idlote);
        RecargarTablaProductos(result);
    }

    private void RecargarTablaProductos(ArrayList<ProductosTaller> list) {

        Object[][] datos = new Object[list.size()][5];
        int i = 0;
        for (ProductosTaller t : list) {
            datos[i][0] = t.getIdpedido();
            datos[i][1] = t.getDescripcion();
            datos[i][2] = t.getCantidad();
            datos[i][3] = t.getEstatus();
            datos[i][4] = t.getDepartamento();
            i++;
        }
        PENDIENTES.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    " ", "DESCRIPCION", "CANTIDAD", "ESTATUS","DEPARTAMENTO"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        TableColumn columna1 = PENDIENTES.getColumn(" ");
        columna1.setPreferredWidth(0);
        TableColumn columna2 = PENDIENTES.getColumn("DESCRIPCION");
        columna2.setPreferredWidth(150);
        TableColumn columna3 = PENDIENTES.getColumn("CANTIDAD");
        columna3.setPreferredWidth(50);
        TableColumn columna4 = PENDIENTES.getColumn("ESTATUS");
        columna4.setPreferredWidth(50);
    }

    private void ListarProductosTrabajosEjemplos() {
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosTrabajoEjemploMaster(idloteejemplo);
        RecargarTablaProductoseje(result);
    }

    private void RecargarTablaProductoseje(ArrayList<ProductosTaller> list) {

        Object[][] datos = new Object[list.size()][5];
        int i = 0;
        for (ProductosTaller t : list) {
            datos[i][0] = t.getIdpedido();
            datos[i][1] = t.getDescripcion();
            datos[i][2] = t.getCantidad();
            datos[i][3] = t.getEstatus();
            datos[i][4] = t.getDepartamento();
            i++;
        }
        PENDIENTESEjemplo.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    " ", "DESCRIPCION", "CANTIDAD", "ESTATUS","DEPARTAMENTO"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        TableColumn columna1 = PENDIENTESEjemplo.getColumn(" ");
        columna1.setPreferredWidth(0);
        TableColumn columna2 = PENDIENTESEjemplo.getColumn("DESCRIPCION");
        columna2.setPreferredWidth(150);
        TableColumn columna3 = PENDIENTESEjemplo.getColumn("CANTIDAD");
        columna3.setPreferredWidth(50);
        TableColumn columna4 = PENDIENTESEjemplo.getColumn("ESTATUS");
        columna4.setPreferredWidth(50);
    }

    private void ListarTrabajosEjemplos() {
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosPendientesEjemploMaster(PNEjemplo.getText());
        RecargarTablaEjemplo(result);
    }

    private void RecargarTablaEjemplo(ArrayList<ProductosTaller> list) {

        Object[][] datos = new Object[list.size()][5];
        int i = 0;
        for (ProductosTaller t : list) {
            datos[i][0] = t.getIdlote();
            datos[i][1] = t.getPN();
            datos[i][2] = t.getJOB();
            datos[i][3] = t.getEstatus();
            datos[i][4] = t.getCantidad();
            i++;
        }
        TrabajosEjemplo.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    " ", "P/N", "JOB", "NO. LOTE", "CANTIDAD"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        TableColumn columna1 = TrabajosEjemplo.getColumn(" ");
        columna1.setPreferredWidth(-20);
        TableColumn columna2 = TrabajosEjemplo.getColumn("P/N");
        columna2.setPreferredWidth(75);
        TableColumn columna3 = TrabajosEjemplo.getColumn("JOB");
        columna3.setPreferredWidth(75);
        TableColumn columna4 = TrabajosEjemplo.getColumn("NO. LOTE");
        columna4.setPreferredWidth(75);
        TableColumn columna5 = TrabajosEjemplo.getColumn("CANTIDAD");
        columna5.setPreferredWidth(75);
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Trabajos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        PENDIENTES = new javax.swing.JTable();
        PN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        po = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        by = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        nota = new javax.swing.JTextArea();
        aceptar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        poInset = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        poPot = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fechapedi = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TrabajosEjemplo = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        PENDIENTESEjemplo = new javax.swing.JTable();
        PNEjemplo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        descripcion2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        fechapedi2 = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        po2 = new javax.swing.JTextField();
        cantidad2 = new javax.swing.JTextField();
        by2 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        nota2 = new javax.swing.JTextArea();
        aceptar3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        poInset1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        poPot1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("ENTREGAS DE PEDIDOS A TALLER");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        Trabajos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "P/N", "JOB", "LOTE", "CANTIDAD"
            }
        ));
        Trabajos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrabajosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Trabajos);

        PENDIENTES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "DESCRIPCION", "FECHA PEDIDO", "ESTADO"
            }
        ));
        PENDIENTES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PENDIENTESMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PENDIENTESMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(PENDIENTES);

        PN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PNKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("P/N");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("TRABAJADO POR ");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("P.O.");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("CANTIDAD");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("NOTA");

        po.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poActionPerformed(evt);
            }
        });

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        by.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byActionPerformed(evt);
            }
        });

        nota.setColumns(20);
        nota.setRows(5);
        jScrollPane3.setViewportView(nota);

        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save2.png"))); // NOI18N
        aceptar.setText("GUARDAR");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("P.O.  INSERT");

        poInset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poInsetActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("P.O. POT ROD");

        poPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poPotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(poPot, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(poInset, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(po, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(144, 144, 144))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(by, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(po, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poInset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(by, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jLabel10.setText("DESCRIPCION");

        descripcion.setEditable(false);

        jLabel11.setText("FECHA DE PEDIDO");

        fechapedi.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechapedi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechapedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 263, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TRABAJOS", jPanel1);

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));

        TrabajosEjemplo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "P/N", "JOB", "LOTE", "CANTIDAD"
            }
        ));
        TrabajosEjemplo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrabajosEjemploMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TrabajosEjemplo);

        PENDIENTESEjemplo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "DESCRIPCION", "FECHA PEDIDO", "ESTADO"
            }
        ));
        PENDIENTESEjemplo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PENDIENTESEjemploMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(PENDIENTESEjemplo);

        PNEjemplo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PNEjemploKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("P/N");

        jLabel24.setText("DESCRIPCION");

        descripcion2.setEditable(false);

        jLabel25.setText("FECHA DE PEDIDO");

        fechapedi2.setEditable(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 133, Short.MAX_VALUE))
                    .addComponent(descripcion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechapedi2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechapedi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setText("TRABAJADO POR ");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("P.O.");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setText("CANTIDAD");

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setText("NOTA");

        po2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                po2ActionPerformed(evt);
            }
        });

        cantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidad2ActionPerformed(evt);
            }
        });

        by2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                by2ActionPerformed(evt);
            }
        });

        nota2.setColumns(20);
        nota2.setRows(5);
        jScrollPane8.setViewportView(nota2);

        aceptar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save2.png"))); // NOI18N
        aceptar3.setText("GUARDAR");
        aceptar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("P.O.  INSERT");

        poInset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poInset1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("P.O. POT ROD");

        poPot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poPot1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(po2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(poInset1)
                            .addComponent(poPot1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(by2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptar3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(po2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poInset1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(poPot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addGap(4, 4, 4)
                        .addComponent(cantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(by2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aceptar3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PNEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNEjemplo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EJEMPLOS", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PNEjemploKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PNEjemploKeyReleased
        ListarTrabajosEjemplos();
    }//GEN-LAST:event_PNEjemploKeyReleased

    private void PENDIENTESEjemploMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PENDIENTESEjemploMouseClicked
        
        //EJEMPLOSSSSSS
        
        String a = (String.valueOf(PENDIENTESEjemplo.getModel().getValueAt(PENDIENTESEjemplo.getSelectedRow(), 3)));
        String b = (String.valueOf(PENDIENTESEjemplo.getModel().getValueAt(PENDIENTESEjemplo.getSelectedRow(), 1)));
        if (a.equalsIgnoreCase("EN PROCESO")) {
            po2.setEnabled(true);
            cantidad2.setEnabled(true);
            by2.setEnabled(true);
            aceptar3.setEnabled(true);
            poInset1.setEnabled(true);
            poPot1.setEnabled(true);
            llenacuainformacionEjemplo();
            if(b.equalsIgnoreCase("HEADER") || b.equalsIgnoreCase("BASES DE FIBRA DE VIDRIO")){
            poInset1.setEnabled(true);
            poPot1.setEnabled(true);}else{poInset1.setEnabled(false);
            poPot1.setEnabled(false);}

        } else {
            po2.setEnabled(false);
            cantidad2.setEnabled(false);
            by2.setEnabled(false);
            aceptar3.setEnabled(false);
            descripcion2.setText("");
            fechapedi2.setText("");
            poInset1.setEnabled(false);
            poPot1.setEnabled(false);
            limpiarEje();

        }
        po2.requestFocus();
    }//GEN-LAST:event_PENDIENTESEjemploMouseClicked

    private void TrabajosEjemploMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrabajosEjemploMouseClicked
        idloteejemplo = (Integer.parseInt(String.valueOf(TrabajosEjemplo.getModel().getValueAt(TrabajosEjemplo.getSelectedRow(), 0))));
        ListarProductosTrabajosEjemplos();
        po2.setEnabled(false);
        cantidad2.setEnabled(false);
        by2.setEnabled(false);
        aceptar3.setEnabled(false);
        descripcion2.setText("");
        fechapedi2.setText("");
        poInset1.setEnabled(false);
        poPot1.setEnabled(false);
        limpiarEje();
    }//GEN-LAST:event_TrabajosEjemploMouseClicked

    private void PNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PNKeyReleased
        ListarTrabajos();
    }//GEN-LAST:event_PNKeyReleased

    private void PENDIENTESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PENDIENTESMouseClicked

        String a = (String.valueOf(PENDIENTES.getModel().getValueAt(PENDIENTES.getSelectedRow(), 3)));
        String b = (String.valueOf(PENDIENTES.getModel().getValueAt(PENDIENTES.getSelectedRow(), 1)));
        idpedidoHistorial = (Integer.parseInt(String.valueOf(PENDIENTES.getModel().getValueAt(PENDIENTES.getSelectedRow(), 0))));
        buscarProducto();
        buscarpo();
        if (a.equalsIgnoreCase("EN PROCESO")) {
            po.setEnabled(true);
            cantidad.setEnabled(true);
            by.setEnabled(true);
            aceptar.setEnabled(true);
            llenacuainformacion();
            if(b.equalsIgnoreCase("HEADER") || b.equalsIgnoreCase("BASES DE FIBRA DE VIDRIO")){
            poInset.setEnabled(true);
            poPot.setEnabled(true);}else{poInset.setEnabled(false);
            poPot.setEnabled(false);}
        }else{
            po.setEnabled(false);
            cantidad.setEnabled(false);
            by.setEnabled(false);
            aceptar.setEnabled(false);
            poInset.setEnabled(false);
            poPot.setEnabled(false);
            descripcion.setText("");
            fechapedi.setText("");
        }
        po.requestFocus();
//aceptar.setEnabled(true);
        //String estado = (String.valueOf(PENDIENTES.getModel().getValueAt(PENDIENTES.getSelectedRow(), 3)));
        //if(estado.equals("ENTREGADO")){aceptar.setEnabled(true);}else{aceptar.setEnabled(false);}
    }//GEN-LAST:event_PENDIENTESMouseClicked

    private void TrabajosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrabajosMouseClicked
        idlote = (Integer.parseInt(String.valueOf(Trabajos.getModel().getValueAt(Trabajos.getSelectedRow(), 0))));
        JobHistorial = String.valueOf(Trabajos.getModel().getValueAt(Trabajos.getSelectedRow(), 2));
        pnHistorial = String.valueOf(Trabajos.getModel().getValueAt(Trabajos.getSelectedRow(), 1));
        ListarProductosTrabajos();
        aceptar.setEnabled(false);
        po.setEnabled(false);
        cantidad.setEnabled(false);
        by.setEnabled(false);
        poInset.setEnabled(false);
        poPot.setEnabled(false);
        limpiar();
    }//GEN-LAST:event_TrabajosMouseClicked

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        if (po.getText().compareTo("") != 0 && cantidad.getText().compareTo("") != 0 && by.getText().compareTo("") != 0) {
            insertarEntrega();
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE TODOS LOS DATOS...");
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void poActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poActionPerformed
        poInset.requestFocus();
    }//GEN-LAST:event_poActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        by.requestFocus();
    }//GEN-LAST:event_cantidadActionPerformed

    private void byActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byActionPerformed

        aceptar.requestFocus();

    }//GEN-LAST:event_byActionPerformed

    private void aceptar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar3ActionPerformed

        if (po2.getText().compareTo("") != 0 && cantidad2.getText().compareTo("") != 0 && by2.getText().compareTo("") != 0) {
            insertarEntregaEjemplo();
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE TODOS LOS DATOS...");
        }


    }//GEN-LAST:event_aceptar3ActionPerformed

    private void po2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_po2ActionPerformed
        cantidad2.requestFocus();
    }//GEN-LAST:event_po2ActionPerformed

    private void cantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidad2ActionPerformed
        by2.requestFocus();
    }//GEN-LAST:event_cantidad2ActionPerformed

    private void by2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_by2ActionPerformed
        aceptar3.requestFocus();
    }//GEN-LAST:event_by2ActionPerformed

    private void poInsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poInsetActionPerformed
       poPot.requestFocus();
    }//GEN-LAST:event_poInsetActionPerformed

    private void poPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poPotActionPerformed
      cantidad.requestFocus();
    }//GEN-LAST:event_poPotActionPerformed

    private void poInset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poInset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poInset1ActionPerformed

    private void poPot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poPot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poPot1ActionPerformed

    private void PENDIENTESMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PENDIENTESMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PENDIENTESMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PENDIENTES;
    private javax.swing.JTable PENDIENTESEjemplo;
    private javax.swing.JTextField PN;
    private javax.swing.JTextField PNEjemplo;
    private javax.swing.JTable Trabajos;
    private javax.swing.JTable TrabajosEjemplo;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton aceptar3;
    private javax.swing.JTextField by;
    private javax.swing.JTextField by2;
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField cantidad2;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField descripcion2;
    private javax.swing.JTextField fechapedi;
    private javax.swing.JTextField fechapedi2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea nota;
    private javax.swing.JTextArea nota2;
    private javax.swing.JTextField po;
    private javax.swing.JTextField po2;
    private javax.swing.JTextField poInset;
    private javax.swing.JTextField poInset1;
    private javax.swing.JTextField poPot;
    private javax.swing.JTextField poPot1;
    // End of variables declaration//GEN-END:variables
}
