/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SolicitudesMateriales;

import BD.BD;
import BD.InsertarProductosTaller;
import BD.ProductosTaller;
import Formularios.Inicio;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class HistorialStatus extends javax.swing.JInternalFrame {
     int idlote;
     int idpedido;
     int depto;
    /**
     * Creates new form STATUS
     */
    public HistorialStatus() {
        initComponents();
        ListarTrabajosTerminados();
        ListarTrabajosTerminadosEjemplo();
        selectusuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     public void selectusuario() {
        String a = System.getProperty("user.name");//usar usuario de windows
        if (a.equals("jluis")) {
            depto = 10;
        } //INFORMATICA
        else if (a.equals("ehernandez")) {
            depto = 1;
        } //TRANSFORMADORES
        else if (a.equals("ingenieria2")) {
            depto = 2;
        } //INGENIERIA
        else if (a.equals("potting")) {
            depto = 3;
        } //STRIP & POTTING
        else if (a.equals("Inspeccion")) {
            depto = 4;
        }// INSPECCION
        else if (a.equals("testing")) {
            depto = 5;
        } // TESTING
        else if (a.equals("calidad")) {
            depto = 6;
        } // CALIDAD 
        else if (a.equals("oecheverria")) {
            depto = 7;
        }//GERENTE OPERACIONES
        else if (a.equals("bodega")) {
            depto = 8;
        }//BODEGA 
        else if (a.equals("ingenieria")) {
            depto = 9;
        }//RELACION CON EL CLIENTE 
        else if(a.equals("taller")){
            depto = 10;
        }//TALLER
        else if(a.equals("Sotano")){
            depto = 10;
        }//TALLER
        else if(a.equals("apacheco")){
            depto = 11;
        }
        else if(a.equals("deptochips")){
            depto = 12;
            
        }
        else if (a.equals("molding")) {
            depto = 13;
        }
    }    
    
    
    
    private void ListarTrabajosTerminados(){
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosTerminados(PN.getText());
        RecargarTabla(result);  
    }
     private void RecargarTabla(ArrayList<ProductosTaller> list) {
         
              Object[][] datos = new Object[list.size()][6];
              int i = 0;
              for(ProductosTaller t : list)
              {
                  datos[i][0] = t.getIdlote();
                  datos[i][1] = t.getPN();
                  datos[i][2] = t.getJOB();
                  datos[i][3] = t.getNolote();
                  datos[i][4] = t.getCantidad();
                  datos[i][5] = t.getPrioridad();
                  i++;
              }    
             Trabajos.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                " ","P/N","JOB","NO. LOTE","CANTIDAD"           })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = Trabajos.getColumn(" ");
             columna1.setPreferredWidth(-20);
             TableColumn columna2 = Trabajos.getColumn("P/N");
             columna2.setPreferredWidth(350);
             TableColumn columna3 = Trabajos.getColumn("JOB");
             columna3.setPreferredWidth(350);
             TableColumn columna4 = Trabajos.getColumn("NO. LOTE");
             columna4.setPreferredWidth(350);
             TableColumn columna5 = Trabajos.getColumn("CANTIDAD");
             columna5.setPreferredWidth(350);   
             } 
     
     private void ListarTrabajosTerminadosEjemplo(){
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosTerminadoEjemplo(PN1.getText());
        RecargarTablaej(result);  
    }
     private void RecargarTablaej(ArrayList<ProductosTaller> list) {
         
              Object[][] datos = new Object[list.size()][5];
              int i = 0;
              for(ProductosTaller t : list)
              {
                  datos[i][0] = t.getIdlote();
                  datos[i][1] = t.getPN();
                  datos[i][2] = t.getJOB();
                  datos[i][3] = t.getEstatus();
                  datos[i][4] = t.getCantidad();
                  i++;
              }    
             Trabajos1.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                " ","P/N","JOB","NO. LOTE","CANTIDAD"          })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = Trabajos1.getColumn(" ");
             columna1.setPreferredWidth(-20);
             TableColumn columna2 = Trabajos1.getColumn("P/N");
             columna2.setPreferredWidth(350);
             TableColumn columna3 = Trabajos1.getColumn("JOB");
             columna3.setPreferredWidth(350);
             TableColumn columna4 = Trabajos1.getColumn("NO. LOTE");
             columna4.setPreferredWidth(350);
             TableColumn columna5 = Trabajos1.getColumn("CANTIDAD");
             columna5.setPreferredWidth(350);   
             }    
    
     private void ListarProductosTrabajosTerminados(){
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosTrabajoTerminadosAceptado(idlote);
        RecargarTablaProductos(result);  
    }
     private void RecargarTablaProductos(ArrayList<ProductosTaller> list){
         
              Object[][] datos = new Object[list.size()][11];
              int i = 0;
              for(ProductosTaller t : list)
              {
                 
                  datos[i][0] = t.getDescripcion();
                  datos[i][1] = t.getCantidad();
                  datos[i][2] = t.getFechaSolicitado();
                  datos[i][3] = t.getFechaStrin();
                  datos[i][4] = t.getCantidadEntre();
                  datos[i][5] = t.getPO();
                  datos[i][6] = t.getPOInsert();
                  datos[i][7] = t.getPOPotRod();
                  datos[i][8] = t.getBy();
                  datos[i][9] = t.getEstatus();
                  datos[i][10] = t.getNota();
                  i++;
              }    
             PENDIENTES.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                "DESCRIPCION","CANTIDAD SOLICITADA","FECHA DE SOLICITUD","FECHA DE ENTREGA","CANTIDAD DE ENTREGA","P.O","P.O INSERT","P.O POT ROD","REALIZADO","ESTADO","NOTA"       })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = PENDIENTES.getColumn("P.O");
             columna1.setPreferredWidth(0);
             TableColumn columna2 = PENDIENTES.getColumn("ESTADO");
             columna2.setPreferredWidth(0);
             TableColumn columna3 = PENDIENTES.getColumn("REALIZADO");
             columna3.setPreferredWidth(0);
             TableColumn columna4 = PENDIENTES.getColumn("P.O INSERT");
             columna4.setPreferredWidth(10);
             TableColumn columna5 = PENDIENTES.getColumn("P.O POT ROD");
             columna5.setPreferredWidth(10);
             }
     
     private void ListarProductosTrabajosTerminadosEjemplo(){
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarProductosTrabajoTerminadosAceptadoEjemplo(idlote);
        RecargarTablaProductosE(result);  
    }
     private void RecargarTablaProductosE(ArrayList<ProductosTaller> list){
         
              Object[][] datos = new Object[list.size()][11];
              int i = 0;
              for(ProductosTaller t : list)
              {
                 
                  datos[i][0] = t.getDescripcion();
                  datos[i][1] = t.getCantidad();
                  datos[i][2] = t.getFechaSolicitado();
                  datos[i][3] = t.getFechaStrin();
                  datos[i][4] = t.getCantidadEntre();
                  datos[i][5] = t.getPO();
                  datos[i][6] = t.getPOInsert();
                  datos[i][7] = t.getPOPotRod();
                  datos[i][8] = t.getBy();
                  datos[i][9] = t.getEstatus();
                  datos[i][10] = t.getNota();
                  i++;
              }    
             PENDIENTES1.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                "DESCRIPCION","CANTIDAD SOLICITADA","FECHA DE SOLICITUD","FECHA DE ENTREGA","CANTIDAD DE ENTREGA","P.O","P.O INSERT","P.O POT ROD","REALIZADO","ESTADO","NOTA"       })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = PENDIENTES1.getColumn("P.O");
             columna1.setPreferredWidth(0);
             TableColumn columna2 = PENDIENTES1.getColumn("ESTADO");
             columna2.setPreferredWidth(0);
             TableColumn columna3 = PENDIENTES1.getColumn("REALIZADO");
             columna3.setPreferredWidth(0);
             TableColumn columna4 = PENDIENTES1.getColumn("P.O INSERT");
             columna4.setPreferredWidth(10);
             TableColumn columna5 = PENDIENTES1.getColumn("P.O POT ROD");
             columna5.setPreferredWidth(10);
             }
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Trabajos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        PENDIENTES = new javax.swing.JTable();
        PN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Trabajos1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        PENDIENTES1 = new javax.swing.JTable();
        PN1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("HISTORIAL PRODUCTOS SOLICITADOS");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        Trabajos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "P/N", "JOB", "LOTE", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Trabajos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrabajosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TrabajosMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Trabajos);

        PENDIENTES.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PENDIENTES.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PENDIENTESMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(PENDIENTES);

        PN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PNKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("P/N");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1310, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TRABAJOS", jPanel1);

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        Trabajos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "P/N", "JOB", "LOTE", "CANTIDAD"
            }
        ));
        Trabajos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Trabajos1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Trabajos1);

        PENDIENTES1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        PENDIENTES1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PENDIENTES1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(PENDIENTES1);

        PN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PN1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PN1KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("P/N");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PN1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1310, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(PN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("EJEMPLOS", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PNKeyReleased
       ListarTrabajosTerminados();
    }//GEN-LAST:event_PNKeyReleased

    private void TrabajosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrabajosMouseClicked
      idlote = (Integer.parseInt(String.valueOf(Trabajos.getModel().getValueAt(Trabajos.getSelectedRow(), 0))));
      ListarProductosTrabajosTerminados();
    }//GEN-LAST:event_TrabajosMouseClicked

    private void PENDIENTESMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PENDIENTESMouseClicked
       
       
    }//GEN-LAST:event_PENDIENTESMouseClicked

    private void Trabajos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Trabajos1MouseClicked
       idlote = (Integer.parseInt(String.valueOf(Trabajos1.getModel().getValueAt(Trabajos1.getSelectedRow(), 0))));
        ListarProductosTrabajosTerminadosEjemplo();
        
    }//GEN-LAST:event_Trabajos1MouseClicked

    private void PENDIENTES1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PENDIENTES1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PENDIENTES1MouseClicked

    private void PN1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PN1KeyReleased
        ListarTrabajosTerminadosEjemplo();
    }//GEN-LAST:event_PN1KeyReleased

    private void PN1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PN1KeyTyped
       
    }//GEN-LAST:event_PN1KeyTyped

    private void TrabajosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrabajosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TrabajosMouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable PENDIENTES;
    private javax.swing.JTable PENDIENTES1;
    private javax.swing.JTextField PN;
    private javax.swing.JTextField PN1;
    private javax.swing.JTable Trabajos;
    private javax.swing.JTable Trabajos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
