/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Consultas;

import BD.InsertTrabajosTransformadores;
import Class.ClassTrabajos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class Historial extends javax.swing.JInternalFrame {
  int id;
    /**
     * Creates new form Historial
     */
    public Historial() {
        initComponents();
        
        ListarTrabajosHistorial();
    }
    
     private void llenacuainformacion() {
       try {
           
            ClassTrabajos c = InsertTrabajosTransformadores.buscarTrabajoTrans(Integer.parseInt(String.valueOf(TaHistorial.getModel().getValueAt(TaHistorial.getSelectedRow(), 0))));
            id = c.getId();
            ListarProcesos();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TaHistorial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        PN = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPro = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HISTORIAL DE PRODUCCION");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 204, 255));
        jPanel1.setFocusTraversalPolicyProvider(true);

        TaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "P/N", "JOB", "CLIENTE", "ESTANDAR", "CANTIDAD", "REVISION", "NO. LOTE"
            }
        ));
        TaHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaHistorialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TaHistorial);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("P/N");

        PN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PNKeyReleased(evt);
            }
        });

        TablaPro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROCESO", "FECHA", "CANTIDAD", "COMENTARIO"
            }
        ));
        TablaPro.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(TablaPro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PNKeyReleased
       ListarTrabajosHistorial();
    }//GEN-LAST:event_PNKeyReleased

    private void TaHistorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaHistorialMouseClicked
        llenacuainformacion();
    }//GEN-LAST:event_TaHistorialMouseClicked

     private void ListarTrabajosHistorial(){
        ArrayList<ClassTrabajos> result = InsertTrabajosTransformadores.ListarHistorial(PN.getText());
        RecargarTabla(result);  
    }
     private void RecargarTabla(ArrayList<ClassTrabajos> list) {
         
              Object[][] datos = new Object[list.size()][8];
              int i = 0;
              for(ClassTrabajos t : list)
              {
                  datos[i][0] = t.getId();
                  datos[i][1] = t.getNOLOTE();
                  datos[i][2] = t.getPN();
                  datos[i][3] = t.getJob();
                  datos[i][4] = t.getCliente();
                  datos[i][5] = t.getEstandar();
                  datos[i][6] = t.getRevision();
                  datos[i][7] = t.getQTYPORLOTE();
                  
                  i++;
              }    
             TaHistorial.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                " ","NO. LOTE","P/N","JOB","CLIENTE","ESTANDAR","REVISION","CANTIDAD"
 
             })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             TableColumn columna1 = TaHistorial.getColumn(" ");
             columna1.setPreferredWidth(0);
             TableColumn columna2 = TaHistorial.getColumn("NO. LOTE");
             columna2.setPreferredWidth(40);
             TableColumn columna3 = TaHistorial.getColumn("P/N");
             columna3.setPreferredWidth(40);
             TableColumn columna4 = TaHistorial.getColumn("JOB");
             columna4.setPreferredWidth(40);
             TableColumn columna5 = TaHistorial.getColumn("CLIENTE");
             columna5.setPreferredWidth(40);
             TableColumn columna6 = TaHistorial.getColumn("ESTANDAR");
             columna6.setPreferredWidth(70);
             TableColumn columna7 = TaHistorial.getColumn("REVISION");
             columna7.setPreferredWidth(40);
             TableColumn columna8 = TaHistorial.getColumn("CANTIDAD");
             columna8.setPreferredWidth(40);
}
     private void ListarProcesos(){
        ArrayList<ClassTrabajos> result1 = InsertTrabajosTransformadores.ListarProceso(id);
        Listar(result1);  
    }
     private void Listar(ArrayList<ClassTrabajos> list1) {
         
              Object[][] datos = new Object[list1.size()][5];
              int i = 0;
              for(ClassTrabajos t : list1)
              {
                  datos[i][0] = t.getProceso();
                  datos[i][1] = t.getFecha();
                  datos[i][2] = t.getCantidad();
                  datos[i][3] = t.getComentarios();
                  datos[i][4] = t.getDepto();
                  i++;
              }    
             TablaPro.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                "PROCESO","FECHA","CANTIDAD","COMENTARIO","DEPARTAMENTO"
             })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
             return false;
             }
             });
             TableColumn columna1 = TablaPro.getColumn("PROCESO");
             columna1.setPreferredWidth(50);
             TableColumn columna2 = TablaPro.getColumn("FECHA");
             columna2.setPreferredWidth(50);
             TableColumn columna3 = TablaPro.getColumn("CANTIDAD");
             columna3.setPreferredWidth(30);
             TableColumn columna4 = TablaPro.getColumn("COMENTARIO");
             columna4.setPreferredWidth(50);
             TableColumn columna5 = TablaPro.getColumn("DEPARTAMENTO");
             columna5.setPreferredWidth(35);
     }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Historial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Historial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PN;
    private javax.swing.JTable TaHistorial;
    private javax.swing.JTable TablaPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
