/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BD.InsertTrabajosTransformadores;
import BD.InsertarEjemplos;
import BD.InsertarProductosTaller;
import BD.ProductosTaller;
import Class.ClassTrabajos;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class HistorialCambios extends javax.swing.JInternalFrame {
     int id;
     int id_new;
     int id_control;
     String Nombre;
     int codigo;
    /**
     * Creates new form HistorialCambios
     */
    public HistorialCambios() {
        initComponents();
        ListarTrabajos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PNINFO = new javax.swing.JTextField();
        JOBINFO = new javax.swing.JTextField();
        CLIENTEINFO = new javax.swing.JTextField();
        ESTANDAR = new javax.swing.JTextField();
        REVISIONINFO = new javax.swing.JTextField();
        FECHAIN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        trabajos = new javax.swing.JTable();
        pn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        JOB = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        proposito = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        consecuencia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        integridad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        solicita = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cambio = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        aprueba = new javax.swing.JTextField();
        fechaautorizacion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        recursos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        CAMBIOS = new javax.swing.JTable();

        jLabel10.setText("REVISION");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("SOLICITA");

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("APRUEBA");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("CAMBIO HECHO");

        setClosable(true);
        setTitle("HISTORIAL DE CAMBIOS");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACION P/N", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("P/N");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("JOB");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("CLIENTE");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("REVISION");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("ESTANDAR");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("FECHA INGRESO");

        PNINFO.setEditable(false);
        PNINFO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PNINFO.setForeground(new java.awt.Color(255, 0, 0));

        JOBINFO.setEditable(false);
        JOBINFO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JOBINFO.setForeground(new java.awt.Color(255, 0, 0));

        CLIENTEINFO.setEditable(false);
        CLIENTEINFO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CLIENTEINFO.setForeground(new java.awt.Color(255, 0, 0));

        ESTANDAR.setEditable(false);
        ESTANDAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ESTANDAR.setForeground(new java.awt.Color(255, 0, 0));

        REVISIONINFO.setEditable(false);
        REVISIONINFO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        REVISIONINFO.setForeground(new java.awt.Color(255, 0, 0));

        FECHAIN.setEditable(false);
        FECHAIN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FECHAIN.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JOBINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PNINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CLIENTEINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ESTANDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(REVISIONINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FECHAIN, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(PNINFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CLIENTEINFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(REVISIONINFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JOBINFO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ESTANDAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(FECHAIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        trabajos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "P/N", "JOB"
            }
        ));
        trabajos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trabajosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(trabajos);

        pn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("P/N");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JOB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JOB.setText("JOB");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORME DE CAMBIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        proposito.setEditable(false);
        proposito.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        proposito.setForeground(new java.awt.Color(0, 51, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("PROPOSITO");

        consecuencia.setEditable(false);
        consecuencia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        consecuencia.setForeground(new java.awt.Color(0, 51, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("CONSECUENCIA");

        integridad.setEditable(false);
        integridad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        integridad.setForeground(new java.awt.Color(0, 51, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("INTEGRIDAD");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("RECURSOS NECESARIOS");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("SOLICITA");

        solicita.setEditable(false);
        solicita.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        solicita.setForeground(new java.awt.Color(0, 51, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("CAMBIO HECHO");

        cambio.setEditable(false);
        cambio.setColumns(20);
        cambio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cambio.setForeground(new java.awt.Color(0, 51, 255));
        cambio.setRows(5);
        jScrollPane3.setViewportView(cambio);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("APRUEBA");

        aprueba.setEditable(false);
        aprueba.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aprueba.setForeground(new java.awt.Color(0, 51, 255));

        fechaautorizacion.setEditable(false);
        fechaautorizacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fechaautorizacion.setForeground(new java.awt.Color(0, 51, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("FECHA AUTORIZACION");

        observaciones.setEditable(false);
        observaciones.setColumns(20);
        observaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        observaciones.setForeground(new java.awt.Color(0, 51, 255));
        observaciones.setRows(5);
        jScrollPane4.setViewportView(observaciones);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("OBSERVACIONES");

        recursos.setEditable(false);
        recursos.setColumns(20);
        recursos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        recursos.setForeground(new java.awt.Color(0, 51, 255));
        recursos.setRows(5);
        recursos.setWrapStyleWord(true);
        jScrollPane5.setViewportView(recursos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel3)
                                .addGap(153, 153, 153)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(proposito, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(consecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(solicita, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aprueba)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaautorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(integridad, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(52, 52, 52))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel13)
                        .addGap(189, 189, 189)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(227, 227, 227))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consecuencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(integridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaautorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aprueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(solicita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        CAMBIOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "INTEGRIDAD", "CAMBIO HECHO", "APRUEBA", "FECHA AUTORIZACION"
            }
        ));
        CAMBIOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CAMBIOSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CAMBIOS);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JOB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JOB)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnKeyTyped
       ListarTrabajos();
    }//GEN-LAST:event_pnKeyTyped

    private void trabajosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trabajosMouseClicked
       Buscar();
       ListarCambios();
       limpiar();
    }//GEN-LAST:event_trabajosMouseClicked

    private void CAMBIOSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CAMBIOSMouseClicked
       BuscarCambio();
       buscarEmpleado();
       aprueba.setText(Nombre);
    }//GEN-LAST:event_CAMBIOSMouseClicked

    private void BuscarCambio() {
        //id_new = (Integer.parseInt(String.valueOf(trabajos.getModel().getValueAt(trabajos.getSelectedRow(), 0))));
         
        try {
            
        ClassTrabajos c = InsertTrabajosTransformadores.buscarTrabajoHistorialFinal(Integer.parseInt(String.valueOf(CAMBIOS.getModel().getValueAt(CAMBIOS.getSelectedRow(),0))));
        proposito.setText(c.getPropositoS());
        consecuencia.setText(c.getConsecuenciaS());
        integridad.setText(c.getIntegridadS());
        solicita.setText(c.getSolicitaS());
        codigo = c.getAprueba();
        fechaautorizacion.setText(c.getFecha());
        cambio.setText(c.getCambio());
        observaciones.setText(c.getObservaciones());  
        recursos.setText(c.getR_fotoS()+"\n"+c.getR_imprimirS()+"\n"+c.getR_materiaS());
        } catch (Exception e) { System.out.println("ERRRORRRRR = "+e);
        }
    }
    
    private void limpiar(){
    
        proposito.setText("");
        consecuencia.setText("");
        integridad.setText("");
        solicita.setText("");
        aprueba.setText("");
        fechaautorizacion.setText("");
        cambio.setText("");
        observaciones.setText(""); 
    
    }
    
    
    private void buscarEmpleado() {
        try {
            ClassTrabajos p = InsertarEjemplos.buscarEmpleado(codigo);
            Nombre = p.getNombres();// + ' ' + p.getApellidos());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRORRRR" + e);
        }
    }
    
    
    
     private void ListarTrabajos() {
        ArrayList<ProductosTaller> result = InsertarProductosTaller.ListarPNHistorial(pn.getText());
        RecargarTablaProductoseje(result);
    }

    private void RecargarTablaProductoseje(ArrayList<ProductosTaller> list) {

        Object[][] datos = new Object[list.size()][3];
        int i = 0;
        for (ProductosTaller t : list) {
            datos[i][0] = t.getIdlote();
            datos[i][1] = t.getPN();
            datos[i][2] = t.getJOB();
            i++;
        }
        trabajos.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    " ", "P/N", "JOB"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
        TableColumn columna1 = trabajos.getColumn(" ");
        columna1.setPreferredWidth(0);
        TableColumn columna2 = trabajos.getColumn("P/N");
        columna2.setPreferredWidth(100);
        TableColumn columna3 = trabajos.getColumn("JOB");
        columna3.setPreferredWidth(100);
        /*TableColumn columna4 = trabajos.getColumn("ESTATUS");
             columna4.setPreferredWidth(120);
             TableColumn columna5 = trabajos.getColumn("FECHA SOLICITUD");
             columna5.setPreferredWidth(220);*/
    }
    
    
    private void Buscar() {
        id_new = (Integer.parseInt(String.valueOf(trabajos.getModel().getValueAt(trabajos.getSelectedRow(), 0))));

        try {

            ClassTrabajos c = InsertTrabajosTransformadores.buscarTrabajoHistorial(Integer.parseInt(String.valueOf(trabajos.getModel().getValueAt(trabajos.getSelectedRow(), 0))));
            id = c.getId();
            PNINFO.setText(c.getPN());
            JOBINFO.setText(c.getJob());
            CLIENTEINFO.setText(c.getCliente());
            REVISIONINFO.setText(c.getRevision());
            ESTANDAR.setText(c.getEstandar());
            FECHAIN.setText(c.getFecha());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error =  " + e);
        }
    }
    
private void ListarCambios() {
        ArrayList<ClassTrabajos> result = InsertTrabajosTransformadores.ListarCambiosRealizadosHistorial2(id_new);
        TablaCambiosRealizados(result);
    }

    private void TablaCambiosRealizados(ArrayList<ClassTrabajos> list) {

        Object[][] datos = new Object[list.size()][5];
        int i = 0;
        for (ClassTrabajos t : list) {
            datos[i][0] = t.getId();
            datos[i][1] = t.getIntegridadS();
            datos[i][2] = t.getCambio();
            datos[i][3] = t.getAprueba();
            datos[i][4] = t.getFecha();
            i++;
        }
        CAMBIOS.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                    "","INTEGRIDAD","CAMBIO HECHO","APRUEBA","FECHA AUTORIZACION"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
        }
        });
        TableColumn columna1 = CAMBIOS.getColumn("");
        columna1.setPreferredWidth(-50);
        TableColumn columna2 = CAMBIOS.getColumn("INTEGRIDAD");
        columna2.setPreferredWidth(0);
        TableColumn columna3 = CAMBIOS.getColumn("CAMBIO HECHO");
        columna3.setPreferredWidth(300);
        TableColumn columna4 = CAMBIOS.getColumn("APRUEBA");
        columna4.setPreferredWidth(20);
        TableColumn columna5 = CAMBIOS.getColumn("FECHA AUTORIZACION");
        columna5.setPreferredWidth(50);
    }   
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CAMBIOS;
    private javax.swing.JTextField CLIENTEINFO;
    private javax.swing.JTextField ESTANDAR;
    private javax.swing.JTextField FECHAIN;
    private javax.swing.JLabel JOB;
    private javax.swing.JTextField JOBINFO;
    private javax.swing.JTextField PNINFO;
    private javax.swing.JTextField REVISIONINFO;
    private javax.swing.JTextField aprueba;
    private javax.swing.JTextArea cambio;
    private javax.swing.JTextField consecuencia;
    private javax.swing.JTextField fechaautorizacion;
    private javax.swing.JTextField integridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JTextField pn;
    private javax.swing.JTextField proposito;
    private javax.swing.JTextArea recursos;
    private javax.swing.JTextField solicita;
    private javax.swing.JTable trabajos;
    // End of variables declaration//GEN-END:variables
}
