/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Ejemplos.RecoridosEjemplos;
import Consultas.Drawings;
import Consultas.EjemplosAprobadosParaTrabajos;
import Consultas.Fotos;
import Consultas.Historial;
import Consultas.HistorialEjemplos;
import Ejemplos.AprobacionEjemplos;
import Ejemplos.IngresoEjemplos;
import java.awt.Dimension;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import Formularios.EditarCantidadLotes;
/**
 *
 * @author jluis
 */
public class Inicio extends javax.swing.JFrame {

    int depto =20;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        }
        initComponents();
        selectusuario();
        this.setExtendedState(MAXIMIZED_BOTH);

        if (depto == 0) {
            nuevotrabajo.setEnabled(true);
            iniciartrabajo.setEnabled(true);
            procesos.setEnabled(true);
            cerrartrabajo.setEnabled(true);
            EDITARCANTIDAD.setEnabled(true);
            nuevoejemplo.setEnabled(true);
            procesoejemplo.setEnabled(true);
            aprobacionejemplo.setEnabled(true);
        } else if (depto == 1)//transformadores
        {
            nuevotrabajo.setEnabled(true);
            iniciartrabajo.setEnabled(true);
            procesos.setEnabled(true);
            cerrartrabajo.setEnabled(true);
            EDITARCANTIDAD.setEnabled(true);
            procesoejemplo.setEnabled(true);
        } else if (depto == 2)//INGENIERIA2
        {
            procesos.setEnabled(true);
           // nuevoejemplo.setEnabled(true);
            procesoejemplo.setEnabled(true);
            aprobacionejemplo.setEnabled(true);
            
        } else if (depto == 3)//potting
        {
            procesos.setEnabled(true);
            procesoejemplo.setEnabled(true);
        } else if (depto == 4)//inspeccio
        {
            procesos.setEnabled(true);
            procesoejemplo.setEnabled(true);
        } else if (depto == 5)//testing
        {
            procesos.setEnabled(true);
            procesoejemplo.setEnabled(true);
        } else if (depto == 6)//calidad    
        {
            procesos.setEnabled(true);
            procesoejemplo.setEnabled(true);
        } else if (depto == 7)//oscar
        {
            procesos.setEnabled(true);
            //nuevoejemplo.setEnabled(true);
            procesoejemplo.setEnabled(true);
            aprobacionejemplo.setEnabled(true);
        }else if (depto == 8)//BODEGA
        {
            procesos.setEnabled(true);
            //nuevoejemplo.setEnabled(true);
            procesoejemplo.setEnabled(true);
           // aprobacionejemplo.setEnabled(true);
        }else if (depto == 9)//RELACION CON EL CLIENTE
        {
            procesos.setEnabled(true);
            nuevoejemplo.setEnabled(true);
            procesoejemplo.setEnabled(true);
            //aprobacionejemplo.setEnabled(true);
        }else if (depto == 10)//TALLER
        {
            procesos.setEnabled(true);
            procesoejemplo.setEnabled(true);
            //aprobacionejemplo.setEnabled(true);
        }
        else if (depto == 10)//TALLER
        {
            procesos.setEnabled(true);
            procesoejemplo.setEnabled(true);
            //aprobacionejemplo.setEnabled(true);
        }
        else if (depto == 11)//GERENCIA
        {
            procesos.setEnabled(true);
           // nuevoejemplo.setEnabled(true);
            procesoejemplo.setEnabled(true);
            aprobacionejemplo.setEnabled(true);
            //aprobacionejemplo.setEnabled(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        Pane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nuevotrabajo = new javax.swing.JMenuItem();
        EDITARCANTIDAD = new javax.swing.JMenuItem();
        iniciartrabajo = new javax.swing.JMenuItem();
        procesos = new javax.swing.JMenuItem();
        cerrartrabajo = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        nuevoejemplo = new javax.swing.JMenuItem();
        procesoejemplo = new javax.swing.JMenuItem();
        aprobacionejemplo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historial de Produccion");

        Pane1.setBackground(new java.awt.Color(255, 255, 255));
        Pane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pane1.setInheritsPopupMenu(true);
        Pane1.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("TRANSFORMADORES");

        jLabel2.setText("jLabel2");

        Pane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Pane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Pane1Layout = new javax.swing.GroupLayout(Pane1);
        Pane1.setLayout(Pane1Layout);
        Pane1Layout.setHorizontalGroup(
            Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pane1Layout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addGroup(Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        Pane1Layout.setVerticalGroup(
            Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 35));

        jMenu1.setText("TRABAJOS");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(5, 25, 5, 25));

        nuevotrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/New.png"))); // NOI18N
        nuevotrabajo.setText("NUEVO TRABAJO");
        nuevotrabajo.setEnabled(false);
        nuevotrabajo.setMargin(new java.awt.Insets(5, 5, 5, 5));
        nuevotrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevotrabajoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevotrabajo);

        EDITARCANTIDAD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit2.png"))); // NOI18N
        EDITARCANTIDAD.setText("EDITAR CANTIDAD DE LOTE");
        EDITARCANTIDAD.setEnabled(false);
        EDITARCANTIDAD.setMargin(new java.awt.Insets(5, 5, 5, 5));
        EDITARCANTIDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITARCANTIDADActionPerformed(evt);
            }
        });
        jMenu1.add(EDITARCANTIDAD);

        iniciartrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1481834876_tick_16.png"))); // NOI18N
        iniciartrabajo.setText("INICIAR TRABAJO");
        iniciartrabajo.setEnabled(false);
        iniciartrabajo.setMargin(new java.awt.Insets(5, 5, 5, 5));
        iniciartrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciartrabajoActionPerformed(evt);
            }
        });
        jMenu1.add(iniciartrabajo);

        procesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ajustes.png"))); // NOI18N
        procesos.setText("PROCESOS");
        procesos.setEnabled(false);
        procesos.setMargin(new java.awt.Insets(5, 5, 5, 5));
        procesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesosActionPerformed(evt);
            }
        });
        jMenu1.add(procesos);

        cerrartrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        cerrartrabajo.setText("CERRAR TRABAJO");
        cerrartrabajo.setEnabled(false);
        cerrartrabajo.setMargin(new java.awt.Insets(5, 5, 5, 5));
        cerrartrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrartrabajoActionPerformed(evt);
            }
        });
        jMenu1.add(cerrartrabajo);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("EJEMPLOS");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(5, 25, 5, 25));

        nuevoejemplo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/New.png"))); // NOI18N
        nuevoejemplo.setText("NUEVO EJEMPLO");
        nuevoejemplo.setEnabled(false);
        nuevoejemplo.setMargin(new java.awt.Insets(5, 5, 5, 5));
        nuevoejemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoejemploActionPerformed(evt);
            }
        });
        jMenu6.add(nuevoejemplo);

        procesoejemplo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ajustes.png"))); // NOI18N
        procesoejemplo.setText("PROCESO EJEMPLO");
        procesoejemplo.setEnabled(false);
        procesoejemplo.setMargin(new java.awt.Insets(5, 5, 5, 5));
        procesoejemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesoejemploActionPerformed(evt);
            }
        });
        jMenu6.add(procesoejemplo);

        aprobacionejemplo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1481834876_tick_16.png"))); // NOI18N
        aprobacionejemplo.setText("APROBACION DE EJEMPLO");
        aprobacionejemplo.setEnabled(false);
        aprobacionejemplo.setMargin(new java.awt.Insets(5, 5, 5, 5));
        aprobacionejemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprobacionejemploActionPerformed(evt);
            }
        });
        jMenu6.add(aprobacionejemplo);

        jMenuBar1.add(jMenu6);

        jMenu4.setText("HISTORIAL");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(5, 25, 5, 25));

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ComponenteImagenes/Report.png"))); // NOI18N
        jMenuItem4.setText("TRABAJOS CERRADOS");
        jMenuItem4.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ComponenteImagenes/OK.png"))); // NOI18N
        jMenuItem1.setText("EJEMPLOS APROBADOS");
        jMenuItem1.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("FOTOS");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(5, 25, 5, 25));

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/camera-icon.png"))); // NOI18N
        jMenuItem6.setText("FOTOS");
        jMenuItem6.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("DRAWINGS");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(5, 25, 5, 25));

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        jMenuItem7.setText("BUSCAR");
        jMenuItem7.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu5.setForeground(new java.awt.Color(255, 0, 0));
        jMenu5.setText("SALIR");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(5, 25, 5, 25));
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jMenuItem5.setText("SALIR");
        jMenuItem5.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane1)
        );

        getAccessibleContext().setAccessibleName("PRODUCCION TRANSFORMADORES");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void selectusuario() {
        String a = System.getProperty("user.name");//usar usuario de windows
        if (a.equals("jluis")) {
            depto = 0;
        } //INFORMATICA
        else if (a.equals("ehernandez")) {
            depto = 1;
        } //TRANSFORMADORES
        else if (a.equals("ingenieria2")) {
            depto = 2;
        } //INGENIERIA
        else if (a.equals("potting")) {
            depto = 3;
        } //STRIP & POTTING
        else if (a.equals("Inspeccion")) {
            depto = 4;
        }// INSPECCION
        else if (a.equals("testing")) {
            depto = 5;
        } // TESTING
        else if (a.equals("calidad")) {
            depto = 6;
        } // CALIDAD 
        else if (a.equals("oecheverria")) {
            depto = 7;
        }//GERENTE OPERACIONES
        else if (a.equals("bodega")) {
            depto = 8;
        }//BODEGA 
        else if (a.equals("ingenieria")) {
            depto = 9;
        }//RELACION CON EL CLIENTE 
        else if(a.equals("taller")){
            depto = 10;
        }//TALLER
        else if(a.equals("sotano")){
            depto = 10;
        }//TALLER
        else if(a.equals("apacheco")){
            depto = 11;
            
        }
        
        jLabel2.setText(a);
    }

    private void nuevotrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevotrabajoActionPerformed
        EjemplosAprobadosParaTrabajos tra = new EjemplosAprobadosParaTrabajos();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();
    }//GEN-LAST:event_nuevotrabajoActionPerformed

    private void procesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesosActionPerformed
        ProcesosTrans tra = new ProcesosTrans();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();
    }//GEN-LAST:event_procesosActionPerformed

    private void cerrartrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrartrabajoActionPerformed

        CerrarTrabajo tra = new CerrarTrabajo();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();

    }//GEN-LAST:event_cerrartrabajoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Historial tra = new Historial();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed


    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        System.exit(1);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Fotos tra = new Fotos();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Drawings tra = new Drawings();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void iniciartrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciartrabajoActionPerformed

        IniciarTrabajoTrans tra = new IniciarTrabajoTrans();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();
    }//GEN-LAST:event_iniciartrabajoActionPerformed

    private void nuevoejemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoejemploActionPerformed
        IngresoEjemplos tra = new IngresoEjemplos();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();
    }//GEN-LAST:event_nuevoejemploActionPerformed

    private void procesoejemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesoejemploActionPerformed
        RecoridosEjemplos tra = new RecoridosEjemplos();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();
    }//GEN-LAST:event_procesoejemploActionPerformed

    private void aprobacionejemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprobacionejemploActionPerformed
        AprobacionEjemplos tra = new AprobacionEjemplos();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();
    }//GEN-LAST:event_aprobacionejemploActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        HistorialEjemplos tra = new HistorialEjemplos();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void EDITARCANTIDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITARCANTIDADActionPerformed
        
        EditarCantidadLotes tra = new EditarCantidadLotes();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.show();
    }//GEN-LAST:event_EDITARCANTIDADActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EDITARCANTIDAD;
    public static javax.swing.JDesktopPane Pane1;
    private javax.swing.JMenuItem aprobacionejemplo;
    private javax.swing.JMenuItem cerrartrabajo;
    private javax.swing.JMenuItem iniciartrabajo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem nuevoejemplo;
    private javax.swing.JMenuItem nuevotrabajo;
    private javax.swing.JMenuItem procesoejemplo;
    private javax.swing.JMenuItem procesos;
    // End of variables declaration//GEN-END:variables
}
