/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BD.InsertTrabajosTransformadores;
import Class.ClassTrabajos;
import java.util.ArrayList;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class TrabajosVencimiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form TrabajosVencimiento
     */
    public TrabajosVencimiento() {
        initComponents();
        ListarTrabajosVencidos();
        Trabajos.setDefaultRenderer (Object.class, new FormatoTablaVencimientos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Trabajos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JOB = new javax.swing.JTextField();
        PN = new javax.swing.JTextField();

        setClosable(true);
        setTitle("ESTADO DE TRABAJOS PENDIENTES");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        Trabajos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "P/N", "JOB", "CLIENTE", "FECHA DE INGRESO", "FECHA INICIO", "MESES DE INICIO", "LOTES PENDIENTES", "ESTADO"
            }
        ));
        Trabajos.setSelectionBackground(new java.awt.Color(153, 204, 255));
        Trabajos.setSelectionForeground(new java.awt.Color(51, 51, 51));
        Trabajos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Trabajos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("P/N");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("JOB");

        JOB.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOBActionPerformed(evt);
            }
        });
        JOB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JOBKeyReleased(evt);
            }
        });

        PN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNActionPerformed(evt);
            }
        });
        PN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PNKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JOB, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1169, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(JOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNActionPerformed
        JOB.requestFocus();
    }//GEN-LAST:event_PNActionPerformed

    private void PNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PNKeyReleased
        ListarTrabajosVencidos();
    }//GEN-LAST:event_PNKeyReleased

    private void JOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOBActionPerformed
        ListarTrabajosVencidos();
    }//GEN-LAST:event_JOBActionPerformed

    private void JOBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JOBKeyReleased
        ListarTrabajosVencidos();
    }//GEN-LAST:event_JOBKeyReleased

    
    
     private void ListarTrabajosVencidos(){
        ArrayList<ClassTrabajos> result = InsertTrabajosTransformadores.ListarTrabajosVencidos(PN.getText(),JOB.getText());
        RecargarTabla(result);  
    }
     private void RecargarTabla(ArrayList<ClassTrabajos> list) {
         
              Object[][] datos = new Object[list.size()][8];
              int i = 0;
              for(ClassTrabajos t : list)
              {
                  //datos[i][0] = t.getId();
                  datos[i][0] = t.getPN();
                  datos[i][1] = t.getJob();
                  datos[i][2] = t.getCliente();
                  datos[i][3] = t.getFecha();
                  datos[i][4] = t.getFecha2();
                  datos[i][5] = t.getLotes();
                  datos[i][6] = t.getMeses();
                  datos[i][7] = t.getEstado();
                  i++;
              }    
             Trabajos.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                "P/N","JOB","CLIENTE","FECHA DE INGRESO","FECHA DE INICIO","LOTES PENDIENTES","MESES EN PRODUCCION","ESTADO DE TRABAJO"
             })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
            
             TableColumn columna2 = Trabajos.getColumn("P/N");
             columna2.setPreferredWidth(50);
             TableColumn columna3 = Trabajos.getColumn("JOB");
             columna3.setPreferredWidth(50);
             TableColumn columna4 = Trabajos.getColumn("CLIENTE");
             columna4.setPreferredWidth(100);
             TableColumn columna5 = Trabajos.getColumn("FECHA DE INGRESO");
             columna5.setPreferredWidth(50);
             TableColumn columna6 = Trabajos.getColumn("FECHA DE INICIO");
             columna6.setPreferredWidth(60);
             TableColumn columna7 = Trabajos.getColumn("LOTES PENDIENTES");
             columna7.setPreferredWidth(50);
             TableColumn columna8 = Trabajos.getColumn("MESES EN PRODUCCION");
             columna8.setPreferredWidth(50);
             TableColumn columna9 = Trabajos.getColumn("ESTADO DE TRABAJO");
             columna9.setPreferredWidth(150);
             
             
}
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JOB;
    private javax.swing.JTextField PN;
    private javax.swing.JTable Trabajos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
