/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import BD.InsertTrabajosTransformadores;
import Class.ClassTrabajos;
import SolicitudesMateriales.FormatoTabla;
import java.util.ArrayList;
import javax.swing.table.TableColumn;

/**
 *
 * @author jluis
 */
public class TrabajosDepartamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form TrabajosDepartamento
     */
    public TrabajosDepartamento() {
        initComponents();
        ListarTrabajosTrans();
        TRABAJOS.setDefaultRenderer (Object.class, new FormatoTabla());
    }

    private void ListarTrabajosTrans(){
        ArrayList<ClassTrabajos> result = InsertTrabajosTransformadores.ListarTrabajosporDepto(descripcion.getText());
        RecargarTabla(result);  
    }
     private void RecargarTabla(ArrayList<ClassTrabajos> list) {
         
              Object[][] datos = new Object[list.size()][7];
              int i = 0;
              for(ClassTrabajos t : list)
              {
                  datos[i][0] = t.getProceso();
                  datos[i][1] = t.getPN();
                  datos[i][2] = t.getJob();
                  datos[i][3] = t.getNOLOTE();
                  datos[i][4] = t.getFecha();
                  datos[i][5] = t.getCantidad();
                  datos[i][6] = t.getPrioridadStrin();
                  i++;
              }    
             TRABAJOS.setModel(new javax.swing.table.DefaultTableModel(
                datos,
                new String[]{
                "PROCESO","P/N","JOB","LOTE","FECHA","CANTIDAD","PRIORIDAD"
             })
             {  
                 @Override
             public boolean isCellEditable(int row, int column){
                 return false;
             }
             });
             
             TableColumn columna1 = TRABAJOS.getColumn("P/N");
             columna1.setPreferredWidth(40);
             TableColumn columna2 = TRABAJOS.getColumn("JOB");
             columna2.setPreferredWidth(40);
             TableColumn columna3 = TRABAJOS.getColumn("PROCESO");
             columna3.setPreferredWidth(150);
             TableColumn columna4 = TRABAJOS.getColumn("LOTE");
             columna4.setPreferredWidth(30);
             TableColumn columna5 = TRABAJOS.getColumn("FECHA");
             columna5.setPreferredWidth(50);
             TableColumn columna6 = TRABAJOS.getColumn("CANTIDAD");
             columna6.setPreferredWidth(40);
             TableColumn columna7 = TRABAJOS.getColumn("PRIORIDAD");
             columna7.setPreferredWidth(50);
             
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TRABAJOS = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();

        setClosable(true);
        setTitle("ORDENES POR DEPARTAMENTO");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        TRABAJOS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "P/N", "JOB", "PROCESO", "LOTE", "FECHA", "CANTIDAD", "PRIORIDAD"
            }
        ));
        jScrollPane1.setViewportView(TRABAJOS);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ORDENES POR DEPARTAMENTO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("BUSCAR");

        descripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripcionKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(503, 503, 503)
                                .addComponent(jLabel1)))
                        .addGap(0, 507, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionKeyReleased

            ListarTrabajosTrans();

    }//GEN-LAST:event_descripcionKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TRABAJOS;
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
